package com.dnbresearch.app.data

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.time.LocalDate

class TrackFilterTest {

    @Test
    fun parsesIsoDurations() {
        assertEquals(253L, TrackFilter.parseIsoDuration("PT4M13S"))
        assertEquals(3600L + 120, TrackFilter.parseIsoDuration("PT1H2M"))
        assertEquals(45L, TrackFilter.parseIsoDuration("PT45S"))
        assertEquals(0L, TrackFilter.parseIsoDuration("garbage"))
    }

    @Test
    fun parsesReleaseDateFromAutoGeneratedDescription() {
        val description = "Provided to YouTube by Hospital Records\n\nTrack · Artist\n\n" +
            "℗ 2026 Hospital Records\n\nReleased on: 2026-09-25\n\nAuto-generated by YouTube."
        assertEquals(LocalDate.of(2026, 9, 25), TrackFilter.parseReleaseDate(description))
        assertTrue(TrackFilter.isOfficialRelease("Artist - Topic", description))
        assertNull(TrackFilter.parseReleaseDate("Out now on all platforms"))
    }

    @Test
    fun detectsMixesButKeepsOriginalAndVipMixes() {
        assertTrue(TrackFilter.isLikelyMix("Liquid DnB Mix 2026", 3600))
        assertTrue(TrackFilter.isLikelyMix("Neurofunk Guest Mix", 600))
        assertTrue(TrackFilter.isLikelyMix("Artist - Live at Let It Roll", 300))
        assertFalse(TrackFilter.isLikelyMix("Artist - Track (Original Mix)", 300))
        assertFalse(TrackFilter.isLikelyMix("Artist - Track (VIP Mix)", 280))
        assertFalse(TrackFilter.isLikelyMix("Artist - Track (Other Artist Remix)", 320))
    }

    @Test
    fun detectsDnbKeywords() {
        assertTrue(TrackFilter.isDnbRelated("New Track", "#drumandbass #dnb"))
        assertTrue(TrackFilter.isDnbRelated("Artist - Tune [Drum & Bass]"))
        assertFalse(TrackFilter.isDnbRelated("Cooking with pasta", "Recipe video"))
    }

    @Test
    fun checksDateWindow() {
        val today = LocalDate.of(2026, 10, 1)
        assertTrue(TrackFilter.isWithinDays(LocalDate.of(2026, 9, 17), 14, today))
        assertTrue(TrackFilter.isWithinDays(today, 14, today))
        assertFalse(TrackFilter.isWithinDays(LocalDate.of(2026, 9, 16), 14, today))
    }
}
